# Generated by Django 5.1.4 on 2026-06-24 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryFoodCpiMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='First day of the month.')),
                ('food_cpi', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('general_cpi', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cpi_points', to='catalog.country')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cpi_points', to='catalog.datasource')),
            ],
            options={
                'db_table': 'prices_country_food_cpi_monthly',
                'ordering': ['country', 'period'],
                'indexes': [models.Index(fields=['country', 'period'], name='ix_country_cpi_country_period')],
                'constraints': [models.UniqueConstraint(fields=('country', 'period'), name='uq_country_cpi_country_period')],
            },
        ),
        migrations.CreateModel(
            name='PriceIndexMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='First day of the month.')),
                ('value_nominal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('value_real', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ingested_at', models.DateTimeField(auto_now=True)),
                ('commodity_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_points', to='catalog.commoditygroup')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_points', to='catalog.datasource')),
            ],
            options={
                'db_table': 'prices_price_index_monthly',
                'ordering': ['commodity_group', 'period'],
                'indexes': [models.Index(fields=['period'], name='ix_price_index_period')],
                'constraints': [models.UniqueConstraint(fields=('commodity_group', 'period'), name='uq_price_index_group_period')],
            },
        ),
    ]
