# Generated by Django 5.1.4 on 2026-07-09 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text="e.g. 'sarima'.", max_length=40)),
                ('model_params', models.JSONField(default=dict)),
                ('train_end', models.DateField(help_text='Last observed period used for fitting.')),
                ('horizon', models.IntegerField(help_text='Number of months forecast forward.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commodity_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_runs', to='catalog.commoditygroup')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forecast_runs', to='catalog.datasource')),
            ],
            options={
                'db_table': 'forecasting_forecast_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='First day of the forecast month.')),
                ('horizon_step', models.IntegerField(help_text='1..H, months ahead of train_end.')),
                ('value_pred', models.DecimalField(decimal_places=2, max_digits=8)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='forecasting.forecastrun')),
            ],
            options={
                'db_table': 'forecasting_forecast_point',
                'ordering': ['run', 'period'],
            },
        ),
        migrations.AddIndex(
            model_name='forecastrun',
            index=models.Index(fields=['commodity_group', 'created_at'], name='ix_forecast_run_group_created'),
        ),
        migrations.AddIndex(
            model_name='forecastpoint',
            index=models.Index(fields=['period'], name='ix_forecast_point_period'),
        ),
        migrations.AddConstraint(
            model_name='forecastpoint',
            constraint=models.UniqueConstraint(fields=('run', 'period'), name='uq_forecast_point_run_period'),
        ),
    ]
